<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>aidl</string>
   </array>
  <key>name</key>
  <string>aidl</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.aidl</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.line.double-slash.aidl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(parcelable|import|package|cpp_header|const|interface|oneway|enum|union|inout|in|out)</string>
          <key>name</key>
          <string>keyword.aidl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(void|boolean|byte|char|short|int|long|float|double)</string>
          <key>name</key>
          <string>storage.type.aidl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(String|CharSequence|List|Map)</string>
          <key>name</key>
          <string>support.class.aidl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#literal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([_a-zA-Z][_a-zA-Z0-9]*)</string>
          <key>name</key>
          <string>text.aidl</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.aidl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.aidl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.aidl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.aidl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.aidl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.aidl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{003a}\x{003b}\x{002c}.\x{003d}\x{002b}\x{002a}\x{002f}\x{0025}\x{0026}\x{007c}\x{0021}\x{007e}\x{003c}\x{003e}\^\-]|&lt;&lt;|&gt;&gt;|&amp;&amp;|\|\||&lt;=|&gt;=|==|!=)</string>
          <key>name</key>
          <string>punctuation.aidl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.illegal.aidl</string>
        </dict>
       </array>
    </dict>
    <key>literal</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&apos;.&apos;)</string>
          <key>name</key>
          <string>constant.character.aidl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&quot;[^\&quot;]*&quot;)</string>
          <key>name</key>
          <string>string.double.aidl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false)</string>
          <key>name</key>
          <string>constant.language.aidl</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.documentation.aidl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.block.documentation.aidl</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.documentation.aidl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.aidl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.block.aidl</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.aidl</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>multi_line_comment__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(0[x\x{007c}X][0-9a-fA-F]+[lL]?)</string>
          <key>name</key>
          <string>constant.numeric.hex.aidl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([0-9]*\.[0-9]+([eE][-\x{002b}]?[0-9]+)?f?|[0-9]*\.?[0-9]+([eE][-\x{002b}]?[0-9]+)?f)</string>
          <key>name</key>
          <string>constant.numeric.float.aidl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([0-9]+[lL]?)</string>
          <key>name</key>
          <string>constant.numeric.decimal.aidl</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
